FROM nginx

RUN rm -rf /usr/share/nginx/html
# COPY public /usr/share/nginx/html

ENV INSTALL_DIR=/install

COPY install/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./install/nginx/nginx_entrypoint.sh ${INSTALL_DIR}/nginx_entrypoint.sh
RUN chmod -R 700 ${INSTALL_DIR}


CMD ${INSTALL_DIR}/nginx_entrypoint.sh