# our base image, for now, Ubuntu
FROM ubuntu:14.04
USER root

# Install dependencies
RUN apt-get update -y 
RUN apt-get install -y python-dev
RUN apt-get install -y openjdk-7-jdk
RUN apt-get install -y python-setuptools
RUN apt-get install -y wget

# Needed for postgres-9.4, which is needed for arches, which is needed to run some elasticsearch install scripts
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  sudo apt-key add -
RUN apt-get update -y
RUN apt-get install -y postgresql-9.4

# Install arches and arches hip, so that we can use their install scripts (for graphs, authority documents, etc)
COPY arches/ /tmp/arches
# Overwrite arches settings, so we are using localhost for the database server
# COPY install/settings_db_arches.py /tmp/arches/arches/settings.py
# COPY install/settings_db_archeship.py /tmp/arches/arches/arches_hip/arches_hip/settings.py

RUN	easy_install pip
WORKDIR /tmp/arches
RUN pip install -e .
RUN python setup.py build
RUN python setup.py install

WORKDIR /tmp/arches/arches/arches_hip
RUN pip install -e .

RUN apt-get install -y libpq-dev
RUN pip install psycopg2 

# Install Elasticsearch
COPY ./install/install_elasticsearch.py /tmp/install/install_elasticsearch.py
COPY ./install/install_elasticsearch_archeship.py /tmp/install/install_elasticsearch_archeship.py
COPY arches/arches/install/requirements.txt /tmp/install/requirements.txt
WORKDIR /tmp/install
RUN python install_elasticsearch.py
RUN python install_elasticsearch_archeship.py