FROM mdillon/postgis:9.5

# Paths for volumes mounted to host
ENV PG_DATA_VOLUME=/var/lib/postgresql/data
ENV PG_LOG_VOLUME=/var/log/postgresql

# Install packages
RUN apt-get update -y &&\
	apt-get install -y wget \
		build-essential \
		libproj-dev \
		libgdal1-dev

# Install Geos
WORKDIR /tmp
RUN	wget http://download.osgeo.org/geos/geos-3.4.2.tar.bz2 &&\
	tar xvfj geos-3.4.2.tar.bz2 &&\
	cd /tmp/geos-3.4.2 &&\
	./configure &&\
	make &&\
	make install &&\
	rm -rf /tmp


# Remove package list to free up space
RUN rm -rf /var/lib/apt/lists/*

COPY ./install/db/db_entrypoint.sh /docker-entrypoint-initdb.d/db_entrypoint.sh

EXPOSE 5432
VOLUME  ["${PG_LOG_VOLUME}", "${PG_DATA_VOLUME}"]