FROM cvast-build.eastus.cloudapp.azure.com:5000/arches-complete

USER root
WORKDIR /

RUN apt-get update -y &&\
	apt-get install -y curl

# Clean up obsolete folders and packages
RUN apt-get purge -y --auto-remove postgis
RUN apt-get purge -y --auto-remove postgresql-9.4
RUN apt-get purge -y --auto-remove postgresql-server-dev-9.4
RUN apt-get purge -y --auto-remove postgresql-contrib-9.4
RUN apt-get autoremove -y
RUN rm -rf /usr/share/postgresql
RUN rm -rf /${WEB_ROOT}

# Remove package list to free up space
RUN rm -rf /var/lib/apt/lists/*

# Install plugin specific for Elasticsearch 1.4 (see https://github.com/elastic/elasticsearch-cloud-aws)
RUN /elasticsearch/bin/plugin -i elasticsearch/elasticsearch-cloud-aws/2.4.2

RUN useradd elasticsearch

ENV ES_DATADIR=/elasticsearch/data
ENV DATA_VOLUME=/elasticsearch-data
ENV CONFIG_VOLUME=/elasticsearch-config
ENV LOG_VOLUME=/elasticsearch-log
ENV INSTALL_DIR=/install

COPY ./install/elasticsearch/elasticsearch.yml ${INSTALL_DIR}/elasticsearch.yml
COPY ./install/elasticsearch/es_entrypoint.sh ${INSTALL_DIR}/es_entrypoint.sh
RUN chmod -R 700 ${INSTALL_DIR}
RUN dos2unix ${INSTALL_DIR}/*



VOLUME ["${DATA_VOLUME}, ${CONFIG_VOLUME}, ${LOG_VOLUME}"]
EXPOSE 9200
ENTRYPOINT ${INSTALL_DIR}/es_entrypoint.sh -Des.config=${CONFIG_VOLUME}/elasticsearch.yml