# our base image
FROM cvast-build.eastus.cloudapp.azure.com:5000/arches-complete

USER root
WORKDIR /

# Path for volumes mounted to host
ENV DATA_VOLUME=/postgres-data
ENV CONFIG_VOLUME=/postgres-config
ENV LOG_VOLUME=${PG_LOGDIR}
ENV INSTALL_DIR=/install
ENV IS_CLEAN_ENV=false

# Remove obsolete folders
RUN rm -rf /arches-cvast
RUN rm -rf /elasticsearch

# Cleanup database
USER postgres	
RUN ${PG_BINDIR}/postgresql start &&\
	psql -d ${PG_DBNAME} -c "VACUUM ANALYZE;" &&\
	${PG_BINDIR}/postgresql stop
USER root

# Entrypoint to setup volume mounts
COPY install/db_entrypoint.sh ${INSTALL_DIR}/db_entrypoint.sh
RUN chmod -R 700 ${INSTALL_DIR}

EXPOSE 5432
VOLUME  ["/var/log/postgresql", "${DATA_VOLUME}", "${CONFIG_VOLUME}"]
CMD ${INSTALL_DIR}/db_entrypoint.sh && start-stop-daemon --start --chuid postgres:postgres --exec /usr/lib/postgresql/9.4/bin/postgres -- -D ${DATA_VOLUME} -c config_file=${CONFIG_VOLUME}/postgresql.conf
