# our base image
FROM cvast-build.eastus.cloudapp.azure.com:5000/arches-complete

USER root
WORKDIR /
RUN rm -rf /arches-cvast

RUN apt-get purge -y postgresql-9.4
RUN apt-get purge -y postgresql-server-dev-9.4
RUN apt-get purge -y postgresql-contrib-9.4
RUN apt-get autoremove -y

ENV ES_DATADIR=/elasticsearch/data
ENV DATA_VOLUME=/elasticsearch-data
ENV CONFIG_VOLUME=/elasticsearch-config
ENV LOG_VOLUME=/elasticsearch-log
ENV INSTALL_DIR=/install

COPY ./install/elasticsearch/elasticsearch.yml ${INSTALL_DIR}/elasticsearch.yml
COPY ./install/elasticsearch/es_entrypoint.sh ${INSTALL_DIR}/es_entrypoint.sh
RUN chmod -R 700 ${INSTALL_DIR}

VOLUME ["${DATA_VOLUME}, ${CONFIG_VOLUME}, ${LOG_VOLUME}"]
EXPOSE 9200
CMD ${INSTALL_DIR}/es_entrypoint.sh && /elasticsearch/bin/elasticsearch -Des.config=${CONFIG_VOLUME}/elasticsearch.yml