# our base image
FROM cvast-build.eastus.cloudapp.azure.com:5000/arches-complete

USER root

RUN apt-get purge -y --auto-remove postgis
RUN apt-get purge -y postgresql-9.4
RUN apt-get purge -y postgresql-server-dev-9.4
RUN apt-get purge -y postgresql-contrib-9.4

RUN apt-get autoremove -y 

RUN rm -rf /elasticsearch

EXPOSE 8000
CMD python manage.py runserver 0.0.0.0:8000
