# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_title', models.CharField(default='Center for Virtualization and Applied Spatial Technologies', max_length=100)),
                ('intro_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('intro_button', models.CharField(default='Learn More', max_length=40)),
                ('news_summary_title', models.CharField(default='News', max_length=120)),
                ('news_summary_link', models.CharField(default='See all News items', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
