# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 21:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(max_length=100)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock())]))]),
        ),
    ]
