# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstagindexpage',
            name='back_button',
        ),
        migrations.AddField(
            model_name='newstagindexpage',
            name='available_tags',
            field=models.CharField(default='Available Tags:', max_length=40),
        ),
        migrations.AddField(
            model_name='newstagindexpage',
            name='no_available_tags',
            field=models.CharField(default='No tags recorded yet.', max_length=40),
        ),
        migrations.AddField(
            model_name='newstagindexpage',
            name='tag_found',
            field=models.CharField(default='Showing pages tagged ', max_length=40),
        ),
        migrations.AddField(
            model_name='newstagindexpage',
            name='tag_not_found',
            field=models.CharField(default='No pages found with tag ', max_length=40),
        ),
    ]
