# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 17:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_tag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(max_length=100)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock())])), ('image_header_left', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(max_length=300)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))]))]),
        ),
    ]
